### PR TITLE
.size -> .count

### PR DESCRIPTION
**Pull request by gmkohler**
hoping this fixes issues with working with Sequel's Dataset

### CODE REVIEW

**Comment by ghost** [comment]
@gmkohler any reason this didn't make it into backend Gemfile.lock?

**Comment by gmkohler** [comment]
IIRC the incompatibility ran deeper than this (something with kaminari) so I gave up on the project.  If we want to start using sequel + pagination in rails (which, hey maybe that's `NewRestaurantOrder`), we should get working on a better fix than this

**Comment by ghost** [comment]
Got it. Should we rollback master here?

**Comment by gmkohler** [comment]
I mean, may as well.  On one hand, I prefer the use of `.count` over `.size`.  On the other hand, I didn't audit this and only was referring to this repo locally.

**Comment by ghost** [comment]
ok as long as it's not going to break anything let's leave it as is #longhair.

The gemfile.lock file should protect us anyway.

**Comment by gmkohler** [comment]
💁

**Comment by gmkohler** [comment]
Honestly I think this was my hold-up (Sequel not supporting this method.  But it has `.order`).  Commenting here so I don't forget.  https://github.com/guanglunw/smart_listing/commit/c0e0975c7e821e66e23357344ad1961997fae93f

**Pull request merged**
